// flow-typed signature: e10ca99ef17237068631ed7166540695
// flow-typed version: <<STUB>>/@callstack/async-storage_v^2.0.3/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@callstack/async-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@callstack/async-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@callstack/async-storage/lib/index.android' {
  declare module.exports: any;
}

declare module '@callstack/async-storage/lib/index.ios' {
  declare module.exports: any;
}

declare module '@callstack/async-storage/lib' {
  declare module.exports: any;
}

declare module '@callstack/async-storage/lib/index.mobile' {
  declare module.exports: any;
}

declare module '@callstack/async-storage/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@callstack/async-storage/lib/index.android.js' {
  declare module.exports: $Exports<'@callstack/async-storage/lib/index.android'>;
}
declare module '@callstack/async-storage/lib/index.ios.js' {
  declare module.exports: $Exports<'@callstack/async-storage/lib/index.ios'>;
}
declare module '@callstack/async-storage/lib/index' {
  declare module.exports: $Exports<'@callstack/async-storage/lib'>;
}
declare module '@callstack/async-storage/lib/index.js' {
  declare module.exports: $Exports<'@callstack/async-storage/lib'>;
}
declare module '@callstack/async-storage/lib/index.mobile.js' {
  declare module.exports: $Exports<'@callstack/async-storage/lib/index.mobile'>;
}
declare module '@callstack/async-storage/lib/types.js' {
  declare module.exports: $Exports<'@callstack/async-storage/lib/types'>;
}
